# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#


development:
  adapter: postgresql
  encoding: unicode
  database: hello_rails_back_end_development
  pool: 5
  username: test
  password: test123


test:
  adapter: postgresql
  encoding: unicode
  database: hello_rails_back_end_test
  pool: 5
  username: test
  password: test123


production:
  adapter: postgresql
  encoding: unicode
  database: hello_rails_back_end_production
  pool: 5
  username: test
  password: test123
